### ISSUE TITLE
Random remarks

### ISSUE THREAD

**Issue by gdalle** [SteffenPL/BoundedDegreeGraphs.jl#3]
Hey there @SteffenPL, 

Taking a very quick look at your code, here are a few things I thought of. We can always structure them later.

- I would separate the various structs into different files to make it clearer which methods belong to which
- Why do you need a new edge type?
- Assertions can be deactivated, better to throw errors for invalid inputs
- Is edge addition type-stable? I'm not sure what the callbacks are for but they could lead to performance issues (see the infamous https://docs.julialang.org/en/v1/manual/performance-tips/#man-performance-captured)

**Comment by SteffenPL** [comment]
Thanks for looking at the project! I'll implement 1/ and 3/ directly. 

About 4/, it seemed to be type-stable here, but I will check it again. 

About 2/, you are actually right. My initial idea of the implementation needed a new edge type, but the more I simplified it, the less it was needed anymore and I did not realize that. I can use the simple edge type from Graphs.jl and define a new `init_edge` function to call `minmax` in the case of undirected graphs.

**Comment by SteffenPL** [comment]
Hi, I implemented 1-3.  

Regarding the `add_edge` operation, that seems to be type stable. (The difference to the example from the Julia docs is that the callbacks are only used internally, but they have a finite lifetime. I think Julia seems smart enough not to capture anything here...) Therefore, I think 4 is also fine. 

If it would be instable, then also this test would fail: https://github.com/SteffenPL/BoundedDegreeGraphs.jl/blob/22443f74a7a50357b44d32ebecd8c3718fa1bd38/test/runtests.jl#L158
